title: Applewood HOA
description: Website for the Applewood HOA in Madison, AL

timezone: America/Chicago
permalink: /meetings/:year/:month/:day/:title.html

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

github:
  - is_project_page: false
