title: Applewood HOA
description: Website for the Applewood HOA in Madison, AL

permalink: /meetings/:year/:month/:day/:title.html

theme: jekyll-theme-cayman

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

github:
    - is_project_page: false
