title: Applewood HOA
description: Website for the Applewood HOA in Madison, AL

timezone: America/Chicago
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/meetings/:year/:month/:day/:title.html'

markdown: kramdown

remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

github:
  - is_project_page: false

header:
  has_nav: true
  nav_links:
    - label: Home
      url: /
      style: link
    - label: Documents
      url: /docs/
      style: link
    - label: Meetings
      url: /meetings/
      style: link
    - label: Operations
      url: /operations.html
      style: link
    - label: HOA Dues
      url: /hoadues.html
      style: link

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "hoadefault"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md