title: Applewood HOA
description: Website for the Applewood HOA in Madison, AL

timezone: America/Chicago
permalink: /meetings/:year/:month/:day/:title.html

markdown: kramdown
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "hoadefault"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

github:
  - is_project_page: false
